### ISSUE TITLE
升级到Edge93之后图标异常

### ISSUE THREAD

**Issue by FireFoxAhri** [Devifish/light-tab-page#1]
![QQ截图20210903194845](https://user-images.githubusercontent.com/14964489/132000618-c894c568-a16e-4ad7-8830-0fae037f9cea.png)

Edge92正常，今天升级93之后变成了黑色

**Comment by Devifish** [comment]
这个貌似是edge93显示高分辨率ico有问题， 换32x32后可以显示下个版本修复
