### ISSUE TITLE
建议修复一下新增搜索引擎的{searchText}字符问题

### ISSUE THREAD

**Issue by ningye-kk** [Devifish/light-tab-page#23]
建议修复一下新增搜索引擎的{searchText}字符问题，比如我自定义了fsou，然后搜索c++，只会出来c的搜索结果，++被两个空格替换掉了，这个很影响体验

**Comment by LiQing-Code** [comment]
和我这个(#18)问题一样 ，不知道啥时候可以修复

**Comment by Devifish** [comment]
下个版本已修复，  工作原因搁置了一年🥲
