### ISSUE TITLE
不忘初心

### ISSUE THREAD

**Issue by vlras9527** [Devifish/light-tab-page#3]
标签页并不缺少华丽而复杂的应用，我为什么选择作者的呢？ 主要原因是因为简洁、实用、够用，我相信大多数选择这一款的都是这个目的， 希望作者不忘初心，简洁、实用为主，华而不实的功能不要堆上去

**Comment by Devifish** [comment]
新添加的并非应用，  数据来源是浏览器最近浏览
> 这个功能很多用户需求较大包括自己， 不需要的设置内可以关闭
