### ISSUE TITLE
功能优化建议

### ISSUE THREAD

**Issue by dongbao666666** [Devifish/light-tab-page#7]
希望使用本地图片当壁纸时打开一个新标签页，会白色 闪一下，，能够优化吗

**Comment by Devifish** [comment]
> 希望使用本地图片当壁纸时打开一个新标签页，会白色 闪一下，，能够优化吗

浏览器渲染速度问题，   换张小些的图片即可（建议500kb左右）

**Comment by dongbao666666** [comment]
你好，我最近忙碌中，无法亲自回复你的邮件。我看到后会尽快给你回复。

**Comment by Devifish** [comment]
> 希望使用本地图片当壁纸时打开一个新标签页，会白色 闪一下，，能够优化吗

其实我自己对壁纸加载做了挺多优化了， 出现闪一下其实是渲染慢了

**Comment by dongbao666666** [comment]
你好，我最近忙碌中，无法亲自回复你的邮件。我看到后会尽快给你回复。
