### ISSUE TITLE
求教，如何使Chrome仅打开新标签页的时候显示书签栏（平时书签栏是隐藏状态）

### ISSUE THREAD

**Issue by youngerruan** [Devifish/light-tab-page#8]
Edge，Firefox均可以实现这个特性，但是Chrome我还没发现怎么设置。不然会搞错，因为在页面内点击书签会默认这个页面打开书签，而不是新标签页打开书签，所以有可能按错。如果只有新标签页显示书签栏的话，就能规避这一错误。

**Comment by Devifish** [comment]
> Edge，Firefox均可以实现这个特性，但是Chrome我还没发现怎么设置。不然会搞错，因为在页面内点击书签会默认这个页面打开书签，而不是新标签页打开书签，所以有可能按错。如果只有新标签页显示书签栏的话，就能规避这一错误。

书签栏的右键菜单里可以设置总是显示

**Comment by graynjo** [comment]
chrome安装后书签栏的默认的行为是只在新标签页中显示，类似于edge的这个选项
![image](https://user-images.githubusercontent.com/49585390/162462933-2d978ccb-444f-43c3-995d-bcb0df7b3265.png)

当安装了插件后，chrome默认的标签栏行为就变成了无论普通页面还是新标签页均不显示，虽然可以在chrome的设置里调节均显示或均不显示的开关，但是无法还原到默认的行为，即只在新标签页中显示标签栏

![image](https://user-images.githubusercontent.com/49585390/162463736-26bba99f-21f3-43ba-8141-a42d5e3bfbbc.png)

对于这个需求，插件本身能做什么吗？还是需要在浏览器的其他flag中实现？

**Comment by miaopan607** [comment]
同问
